### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by ItsAtlant** [ItsAtlant/Python-Lezione#2]
- [ ] Tradurre i testi in italiano
- [ ] Scrivere il Readme
- [ ] Finire i programmi incompleti
- [ ] Commentare ogni codice 
- [ ] Fare i programmi che non ho fatto del prof
